### ISSUE TITLE
Copyright isn't fixed on bottom.

### ISSUE THREAD

**Issue by Vedaad-Shakib** [Vedaad-Shakib/HHMS#15]
See following picture:

![](https://cloud.githubusercontent.com/assets/3393996/6353364/c3d2e296-bbfd-11e4-8e51-2f3e74326f23.png)

There is a random white strip on the bottom.

**Comment by Andrew-Tierno** [comment]
It hugs the bottom of the table because the table is of variable length. If I fix it for the case when the table doesn't overflow, then the white strip will appear above the copyright even when it does overflow. Alternatively we could go back to the style where the copyright hovers at the bottom of the screen at all times

**Comment by Vedaad-Shakib** [comment]
I think it would be best to just have some alternating white and grey buffer between the schedule and the copyright similar to the color pattern of the schedule in cases like this where the entire schedule occupies less than a page. 

Is that feasible?

**Comment by Vedaad-Shakib** [comment]
So are we not going to fix this?
